CXX = g++

CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors

SRC1 = nn.cpp
SRC2 = main.cpp
SRCS = ${SRC1} ${SRC2}

HEADER1 = nn.hpp

PROG1 = nn

default:
	${CXX} ${CXXFLAGS} ${SRCS} ${HEADER1} -o ${PROG1}
